declare module '@/api' {
  export const freezingExportAreaLog: IRequestFunc
  export const expFineMerDetail: IRequestFunc
  export const beneficiatedBurdenMaterialSynthesizeExport: IRequestFunc
  export const expMixMerList: IRequestFunc
  export const expMixMerDetail: IRequestFunc
  export const madepkgStationExportSyntData: IRequestFunc
  export const madepkgStationExportGetLineLog: IRequestFunc
  export const killGermPanMonitorExportlogList: IRequestFunc
  export const killGermPanMonitorExportlogByPanId: IRequestFunc
  export const exportAreaLog: IRequestFunc
  export const sproutStationExportSyntData: IRequestFunc
  export const sproutStationExportDetail: IRequestFunc
  export const substrateExport: IRequestFunc
  export const mixtureExport: IRequestFunc
  export const trainHouseExportSyntData: IRequestFunc
  export const liquidGermExportSyntData: IRequestFunc
  export const outoMushWebSynthesizeExport: IRequestFunc
  export const outoMushroomHouseWebDetailExport: IRequestFunc
  export const prodcdutionExport: IRequestFunc
  export const prodattendanceExport: IRequestFunc
  export const prodmadeUpListExport: IRequestFunc
  export const prodstorageTotalExport: IRequestFunc
  export const packroomsynthesizeDateExport: IRequestFunc
  export const packroomdetailDateExport: IRequestFunc
  export const cutMushroomStatSynthesizeExport: IRequestFunc
  export const cutMushroomStatDetailExport: IRequestFunc
  export const settlingMicrobeListExport: IRequestFunc
  export const settlingMicrobeDetailExport: IRequestFunc
  export const materialPutSynthesizeExport: IRequestFunc
  export const AccessBankWebQueryDataExport: IRequestFunc
  export const cutMushroomStatExportSyntData: IRequestFunc
  export const packagingWebworkEfficiencyExport: IRequestFunc
  export const madepkgWorkshopExportSyntData: IRequestFunc
  export const madepkgWorkshopExportDetailData: IRequestFunc
  export const trainWorkshopExportSyntData: IRequestFunc
  export const trainWorkshopExportDetailData: IRequestFunc
  export const outoMushroomWorkshopExportSyntData: IRequestFunc
  export const outoMushroomWorkshopExportDetailData: IRequestFunc
  export const dgstCheckExportSyntData: IRequestFunc
  export const wfMadepkgStationExportSummary: IRequestFunc
  export const wfSproutStationExportSummary: IRequestFunc
  export const qualityExportSyntData: IRequestFunc
  export const qualityExportDetailData: IRequestFunc
  export const qualityVaccinationListExportList: IRequestFunc
  export const qualityVaccinationExportInfo: IRequestFunc
  export const qualityMakePageExportList: IRequestFunc
  export const qualityMakePageExportInfo: IRequestFunc
  export const qualityPackagingExportList: IRequestFunc
  export const qualityPackagingExportInfo: IRequestFunc
  export const qualityDeptQuaExportList: IRequestFunc
  export const qualityDeptQuaExportInfo: IRequestFunc
  export const qualTracExportList: IRequestFunc
  export const expFineMerList: IRequestFunc
}
